BEGIN;

ALTER TABLE teams
ADD COLUMN rank INTEGER,
ADD COLUMN points INTEGER,
ADD COLUMN goals_for INTEGER,
ADD COLUMN goals_against INTEGER,
ADD COLUMN group_id INTEGER;

ALTER TABLE teams
ADD CONSTRAINT fk_group
FOREIGN KEY (group_id)
REFERENCES groups (id)
ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

COMMIT;
